name: Python checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

        - name: Set up Python
          run: uv python install

        - name: Install dependencies
          run: |
            uv sync --dev
        - name: Lint with ruff
          run: uv run ruff check .
        - name: Check formatting with black
          run: uv run black . --check --verbose
        - name: Run unit tests with coverage
          run: |
            uv run pytest
